### PR TITLE
added formData option to readme, version bump

### LINKED ISSUE #38: inserting options.images.formData for upload handling
Hi, I'm hoping for some guidance on where to put this code most efficiently; not a high priority though. Related to https://github.com/bevacqua/bureaucracy/issues/2

I found that `bureaucracy` is in `prompts/prompt.js` and there's an opportunity to pass in an options object here: 

https://github.com/bevacqua/woofmark/blob/b58efb794f7610c92d70bec435cfd021ab45673c/src/prompts/prompt.js#L111-L115

To link that to the `options` object in the `woofmark` constructor, looks like changes would be needed in these two lines (for two modes):

https://github.com/bevacqua/woofmark/blob/b58efb794f7610c92d70bec435cfd021ab45673c/src/html/linkOrImageOrAttachment.js#L27

https://github.com/bevacqua/woofmark/blob/b58efb794f7610c92d70bec435cfd021ab45673c/src/markdown/linkOrImageOrAttachment.js#L111

...then we can access `editor.options` on this line, passing it to `linkOrImageOrAttachment()`:

https://github.com/bevacqua/woofmark/blob/b58efb794f7610c92d70bec435cfd021ab45673c/src/uploads.js#L35

If that looks good, I can do up a PR -- again, not super urgent. Thanks.

### PR DESCRIPTION
**Pull request by jywarren**
Version bump to 1.1.0 (sound right?) and readme update. I'd like to do this so I can resolve https://github.com/bevacqua/woofmark/issues/38 as well. Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, and if you could `npm publish` as well, that'd be awesome.

**Comment by bevacqua** [comment]
Undo the version change and I'll merge the doc update. I had already published as patch

**Comment by jywarren** [comment]
Oh, ok -- hadn't seen the updated package.json, sorry.

**Comment by jywarren** [comment]
OK, there it is!

**Pull request merged**
